# Generated by Django 3.1.3 on 2021-01-15 23:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Medicamentos', '0002_cliente_empleado_empresafarmaceutica_ordendecompra_presentacion_producto_producto_has_proveedor_prov'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='productoMainImg',
            field=models.ImageField(default=datetime.datetime(2021, 1, 15, 23, 14, 31, 224702, tzinfo=utc), upload_to='productos/'),
            preserve_default=False,
        ),
    ]
