# Generated by Django 3.1.3 on 2021-01-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicamentos', '0006_auto_20210118_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
