# Generated by Django 3.1.3 on 2021-01-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicamentos', '0009_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Estante',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='idEmpresaFarmaceutica',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='idPresentacion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
    ]
